### ISSUE TITLE
More Errors

### ISSUE THREAD

**Issue by tristanmoney** [afourney/aprstastic#27]
Here are some more errors that I experienced. I CTRL-C'ed and restarted aprstastic and that seemed to fix it.

DEBUG:aprstastic:Sending to APRS: VE7TMX-5>APZMAG,WIDE1-1,qAR,VE7TMX-10:@030150z5404.06N/12838.91W>aprstastic: !43b582f4
INFO:aprstastic:!435986d8 -> ^all: TELEMETRY_APP
INFO:aprstastic:!435986d8 -> ^all: POSITION_APP
ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

INFO:aprstastic:!7c5b2e9c -> ^all: TELEMETRY_APP
INFO:aprstastic:!9bc1d171 -> ^all: POSITION_APP
INFO:aprstastic:!433aa260 -> ^all: POSITION_APP

====================================================================================

INFO:aprstastic:!433b0ef4 -> ^all: POSITION_APP
INFO:aprstastic:!433e872c -> ^all: POSITION_APP
ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

INFO:aprstastic:!0e56a4e0 -> ^all: POSITION_APP
INFO:aprstastic:!43b582f4 -> ^all: POSITION_APP

====================================================================================

INFO:aprstastic:!4358ef54 -> ^all: TELEMETRY_APP
INFO:aprstastic:!435986d8 -> ^all: POSITION_APP
ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

INFO:aprstastic:!9178aa1c -> ^all: NODEINFO_APP
ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

INFO:aprstastic:!433aa260 -> ^all: POSITION_APP
INFO:aprstastic:!9bc1d171 -> ^all: POSITION_APP

**Comment by afourney** [comment]
I've seen this, but it's intermittent. Hard to reproduce reliably. I'll add logging, and try to track this down.

**Comment by tristanmoney** [comment]
Another one below. Messaging still working though.

INFO:aprstastic:!0e56a4e0 -> ^all: POSITION_APP
INFO:aprstastic:!4358ef54 -> ^all: TELEMETRY_APP
ERROR:root:Unexpected error in deferred execution <class 'pubsub.core.topicargspec.SenderUnknownMsgDataError'>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/util.py", line 288, in _run
    o()
  File "/home/pi/.local/lib/python3.10/site-packages/meshtastic/mesh_interface.py", line 1383, in <lambda>
    lambda: pub.sendMessage(topic, packet=asDict, interface=self)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/publisher.py", line 216, in sendMessage
    topicObj.publish(**msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicobj.py", line 433, in publish
    self._getListenerSpec().check(msgData)
  File "/home/pi/.local/lib/python3.10/site-packages/pubsub/core/topicargspec.py", line 229, in check
    raise SenderUnknownMsgDataError(self.topicNameTuple,
pubsub.core.topicargspec.SenderUnknownMsgDataError: Some optional args unknown in call to sendMessage('('meshtastic', 'receive')', packet,interface): interface

INFO:aprstastic:!435986d8 -> ^all: POSITION_APP
INFO:aprstastic:!9178aa1c -> ^all: NODEINFO_APP

**Comment by tristanmoney** [comment]
Still getting these errors occasionally in 0.0.1a21.

**Comment by tristanmoney** [comment]
The errors were coming in fairly regularly, but I am not getting them this morning. Aprstastic continues to work despite the errors. I will let you know if they start happening again and post details.

**Comment by tristanmoney** [comment]
I have yet to receive these errors again. I even restarted aprstastic. I will close and reopen if it comes back.

**Comment by tristanmoney** [comment]
I have yet to receive these errors again. I even restarted aprstastic. I will close and reopen if it comes back.
